source 'https://github.com/CocoaPods/Specs.git'
source 'git@github.com:mirego/MCPodSpecs.git'

target 'MRGRoundButton', :exclusive => true do
  pod "MRGRoundButton", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "MRGRoundButton", :path => "../"
end
